[package]
name = "chainsaw_gui"
version = "0.0.1"
edition = "2021"

[dependencies]
egui = "0.28.1"
eframe = "0.28.1"
csv = "1.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
petgraph = "0.6.5"
nfd = "0.0.4"

